{
 "title": "Compliance (K8s)",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Compliance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Overall Pass %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "compliance.k8s-bench.pass_pct", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Overall Pass % Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "compliance.k8s-bench.pass_pct", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Pass % By Section",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.1.api-server.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "max",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.2.scheduler.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.3.controller-manager.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.4.configure-files.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.5.etcd.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.6.general-security-primitives.pass_pct",
     "timeAggregation": "max"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.1.kubelet.pass_pct",
     "timeAggregation": "max"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.2.configuration-files.pass_pct",
     "timeAggregation": "max"
    }
   ]
  },
  {
   "title": "Pass % By Section Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.1.api-server.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.2.scheduler.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.3.controller-manager.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.4.configure-files.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.5.etcd.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.6.general-security-primitives.pass_pct",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.1.kubelet.pass_pct",
     "timeAggregation": "max"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.2.configuration-files.pass_pct",
     "timeAggregation": "max"
    }
   ]
  },
  {
   "title": "Test Details (1.1 - API Server)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.1.api-server.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.1.api-server.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.1.api-server.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (Overall)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (1.3 - Controller Manager)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.3.controller-manager.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.3.controller-manager.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.3.controller-manager.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (1.2 - Scheduler)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.2.scheduler.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.2.scheduler.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.2.scheduler.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (1.5 - Etcd)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.5.etcd.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.5.etcd.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.5.etcd.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (1.4 - Configure Files)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.4.configure-files.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.4.configure-files.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.4.configure-files.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (1.6 - General Security Primitives)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.6.general-security-primitives.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.6.general-security-primitives.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.1.6.general-security-primitives.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (2.1 - Kubelet)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.1.kubelet.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.1.kubelet.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.1.kubelet.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Test Details (2.2 - Configuration Files)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.2.configuration-files.tests_pass",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.2.configuration-files.tests_warn",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "target": "compliance.k8s-bench.2.2.configuration-files.tests_fail",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}