{
 "title": "Container Limits",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Hosts & Containers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Shares Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.name" ],
     "target": "cpu.shares.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU Quota Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.name" ],
     "target": "cpu.quota.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Limit Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.name" ],
     "target": "memory.limit.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.name" ],
     "target": "memory.limit.bytes",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}