{
 "title": "Executive Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "label_values(repository)" }
  ]
 },
 "panels": [
  {
   "title": "Pull Request Size",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of Changed Lines" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h])",
     "legendFormat": "{{project}} PR #{{pull_request_number}}"
    }
   ]
  },
  {
   "title": "Pull Requests Over the Past Week",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "max(max_over_time(pr_report_changed_lines{project=~\"$project\"}[7d]))",
     "legendFormat": "Max Pull Request Size"
    },
    {
     "expr": "min(min_over_time(pr_report_changed_lines{project=~\"$project\"}[7d]))",
     "legendFormat": "Min Pull Request Size"
    }
   ]
  },
  {
   "title": "Pull Requests Over the Past Month",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "max(max_over_time(pr_report_changed_lines{project=~\"$project\"}[30d]))",
     "legendFormat": "Max Pull Request Size"
    },
    {
     "expr": "min(min_over_time(pr_report_changed_lines{project=~\"$project\"}[30d]))",
     "legendFormat": "Min Pull Request Size"
    }
   ]
  },
  {
   "title": "Pull Request Size",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Number of Changed Lines" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h])",
     "legendFormat": "{{project}} PR #{{pull_request_number}}"
    }
   ]
  },
  {
   "title": "Pull Requests Over the Past 3 Months",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "max(max_over_time(pr_report_changed_lines{project=~\"$project\"}[90d]))",
     "legendFormat": "Max Pull Request Size"
    },
    {
     "expr": "min(min_over_time(pr_report_changed_lines{project=~\"$project\"}[90d]))",
     "legendFormat": "Min Pull Request Size"
    }
   ]
  },
  {
   "title": "Pull Request Size",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Number of Changed Lines" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h])",
     "legendFormat": "{{project}} PR #{{pull_request_number}}"
    }
   ]
  },
  {
   "title": "Average Pull Request Size",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "count(avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h]))",
     "legendFormat": "Number of PRs"
    },
    {
     "expr": "avg(avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h]))",
     "legendFormat": "Average Number of Changed Lines"
    }
   ]
  },
  {
   "title": "Average Pull Request Size",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 30 },
   "targets": [
    {
     "expr": "count(avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h]))",
     "legendFormat": "Number of PRs"
    },
    {
     "expr": "avg(avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h]))",
     "legendFormat": "Average Number of Changed Lines"
    }
   ]
  },
  {
   "title": "Average Pull Request Size",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "count(avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h]))",
     "legendFormat": "Number of PRs"
    },
    {
     "expr": "avg(avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h]))",
     "legendFormat": "Average Number of Changed Lines"
    }
   ]
  }
 ]
}