{
 "title": "HTTP",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Applications"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.http.request.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "HTTP Error Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.http.error.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.http.request.time", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Max Request Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.http.request.time.worst", "timeAggregation": "max" }
   ]
  },
  {
   "title": "Number of Requests Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.http.request.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Average and Max Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.http.request.time", "timeAggregation": "avg" },
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.http.request.time.worst", "timeAggregation": "max" }
   ]
  },
  {
   "title": "Top URLs by Number of Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.http.url" ],
     "target": "net.http.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Slowest URLs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.http.url" ],
     "target": "net.http.request.time.worst",
     "timeAggregation": "max"
    }
   ]
  },
  {
   "title": "Status Codes Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.http.statusCode" ],
     "target": "net.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Request Types Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.http.method" ],
     "target": "net.http.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}