{
 "title": "Integration Metrics",
 "tags": [ "CI-Pipeline" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "label_values(repository)" },
   {
    "name": "job_number",
    "label": "Job Number",
    "query": "label_values(jenkins_build_status, job_number)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Build Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_build_status{project=~\"$project\", job_number=~\"$job_number\"}"
    }
   ]
  },
  {
   "title": "Results for system_metadata",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "jenkins_seed_tests_type{project=~\"$project\", job_number=~\"$job_number\", a_name=\"system_metadata\"}"
    },
    {
     "expr": "jenkins_seed_total_tests{project=~\"$project\", job_number=~\"$job_number\", a_name=\"system_metadata\"}"
    }
   ]
  },
  {
   "title": "Test Total Run Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jenkins_seed_tests_total_run_duration{project=~\"$project\", job_number=~\"$job_number\"}",
     "legendFormat": "{{a_name}}"
    }
   ]
  },
  {
   "title": "Test Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "jenkins_seed_total_tests{project=~\"$project\", job_number=~\"$job_number\"}"
    }
   ]
  },
  {
   "title": "Test Average Response Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jenkins_seed_tests_average_response_time{project=~\"$project\", job_number=~\"$job_number\"}",
     "legendFormat": "{{a_name}}"
    }
   ]
  },
  {
   "title": "Total Data Received",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jenkins_seed_tests_total_data_received{project=~\"$project\", job_number=~\"$job_number\"}",
     "legendFormat": "{{a_name}}"
    }
   ]
  }
 ]
}