{
 "title": "Jenkins: Performance and Health Overview",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage, Jenkins Job Status, and lot more.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "query": "label_values(jenkins_job)" },
   { "name": "job", "query": "label_values(jenkins_job)" }
  ]
 },
 "panels": [
  {
   "title": "Last Build Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result{jenkins_job=~\"$project\"}"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "default_jenkins_builds_duration_milliseconds_summary_sum{jenkins_job=~\"$project\"}",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Total Number of Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(jenkins_runs_total_total[24h])"
    }
   ]
  },
  {
   "title": "Total Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(jenkins_runs_success_total[24h])"
    }
   ]
  },
  {
   "title": "Total Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(jenkins_runs_failure_total[24h])"
    }
   ]
  },
  {
   "title": "Total Unstable Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(jenkins_runs_unstable_total[24h])"
    }
   ]
  },
  {
   "title": "Total Aborted Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(jenkins_runs_aborted_total[24h])"
    }
   ]
  },
  {
   "title": "Total Not Built Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(jenkins_runs_not_built_total[24h])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  }
 ]
}