{
 "title": "Kubernetes Nodes State",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pods Ready by Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "kubernetes.pod.status.ready",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Nodes Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.node.ready", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.node.unschedulable", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Nodes Network Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.node.networkUnavailable",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Nodes Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.node.memoryPressure", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Nodes Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.node.diskPressure", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.node.outOfDisk", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Pod Capacity Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "memory.bytes.used",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.node.capacity.pods",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.node.capacity.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.node.capacity.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Total CPU Allocatable Capacity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.node.allocatable.cpuCores",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Total Memory Allocatable Capacity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.node.allocatable.memBytes",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}