{
 "title": "Kubernetes Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Pod Phase (entity-matching-service)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"default\",pod=\"entity-matching-service-fdf4f64c9-7p6mg\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Number of Container Restarts",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"default\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Status Ready To Serve Requests (entity-matching-service)",
   "type": "gauge",
   "description": "Describes whether the pod is ready to serve requests.",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"default\",pod=\"entity-matching-service-fdf4f64c9-7p6mg\",condition=\"true\"}"
    }
   ]
  },
  {
   "title": "Current Pod Container Status (entity-matching-service)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=\"default\",pod=\"entity-matching-service-fdf4f64c9-7p6mg\",container=\"entity-matching-service\"}"
    }
   ]
  },
  {
   "title": "Pod Status Waiting (entity-matching-service)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting{namespace=\"default\",pod=\"entity-matching-service-fdf4f64c9-7p6mg\",container=\"entity-matching-service\"}"
    }
   ]
  },
  {
   "title": "Reason for Waiting",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"default\",pod=\"entity-matching-service-fdf4f64c9-7p6mg\",container=\"entity-matching-service\"}",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}