{
 "title": "Kubernetes Pod Health",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Resource Usage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Count by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "net.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Response Time by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "net.request.time",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Bytes In by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "net.bytes.in",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU % by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Memory Used by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "memory.bytes.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "File System % by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "fs.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "File I/O by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "file.time.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Net Error Count by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "net.error.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Bytes Out by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "net.bytes.out",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Container Count Distribution by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 100,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Container Count by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Restarts by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "kubernetes.pod.restart.count",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "CPU Shares Used % by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "cpu.shares.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU Quota Used % by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "cpu.quota.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Limit Used by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}