{
 "title": "Kubernetes Stateful State",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "No. of Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "avg",
     "target": "kubernetes.statefulSet.status.replicas.ready",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Container Count by Statefulset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.statefulSet.name" ],
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Restarts by StatefulSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.statefulSet.name" ],
     "target": "kubernetes.pod.restart.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Desired by StatefulSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.statefulSet.name" ],
     "target": "kubernetes.statefulSet.replicas",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods by StatefulSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.statefulSet.name" ],
     "target": "kubernetes.statefulSet.status.replicas.ready",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Capacity Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "cpu.shares.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}