{
 "title": "Kubernetes Daemonset State",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pods Ready by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "target": "kubernetes.daemonSet.pods.ready",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Misscheduled by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "target": "kubernetes.daemonSet.pods.misscheduled",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pods Desired by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "target": "kubernetes.daemonSet.pods.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Scheduled by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "target": "kubernetes.daemonSet.pods.scheduled",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}