{
 "title": "Kubernetes Service Golden Signals",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Services"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Response Time per Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.request.time",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Request Rate per Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Error Rate (4xx/5xx) per Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.error.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Slowest Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.http.url" ],
     "target": "net.http.request.time",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Most Requested Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "net.http.url" ],
     "target": "net.http.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Endpoints with most error rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "net.http.url" ],
     "target": "net.http.error.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "My Services",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.request.time",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.request.count",
     "timeAggregation": "timeAvg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.error.count",
     "timeAggregation": "timeAvg"
    },
    {
     "groupAggregation": "concat",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.statusCode",
     "timeAggregation": "concat"
    }
   ]
  },
  {
   "title": "CPU Used per Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Memory Used per Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Storage Used per Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "fs.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Network I/O per Service",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Response Time Distribution for Services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 100,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.request.time",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Request Rate Distribution for Services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 100,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Error Rate Distribution for Services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 100,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "net.http.error.count",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}