{
 "title": "Kubernetes Control Plane Health",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Resource Usage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Kube Control Plane File I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 50,
     "segmentBy": [ "proc.name" ],
     "sortDirection": "desc",
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Kube Control Plane Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 50,
     "segmentBy": [ "proc.name" ],
     "sortDirection": "desc",
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  { "title": "title", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 }, "content": "## Kube Control Plane Health" },
  {
   "title": "Kube Control Plane Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "sortDirection": "desc",
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  { "title": "Master Health", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "## Master Health" },
  {
   "title": "Kubernetes Master Health",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    },
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    },
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    },
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "title",
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 22 },
   "content": "## H2 Kube Controller Manager Health"
  },
  {
   "title": "Kube Control Plane CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "sortDirection": "desc",
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Kube Controller Manager CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 50,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Kube ETCD Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Kube Controller Manager Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 50,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Kube Controller Manager File I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Master Components",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "content": "<div class=\"text-center muted\"><strong>Topology</strong> cannot be exported from Sysdig Monitor to Grafana.</div>"
  },
  {
   "title": "Kube ETCD CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 50,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Kube ETCD File I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Kube ETCD Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Kube Controller Manager File I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Kube Ingress-Controller  CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 50,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Kube Ingress-Controller Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Kube Ingress-Controller  Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Kube Ingress-Controller File I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "proc.name in (\"kube-controller\", \"kube-apiserver\", \"kube-scheduler\", \"etcd\")",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.node.name",
      "proc.name"
     ],
     "sortDirection": "desc",
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  { "title": "title", "type": "text", "gridPos": { "h": 2, "w": 22, "x": 0, "y": 30 }, "content": "##  Kube ETCD Health" },
  {
   "title": "title",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "content": "## Kube Ingress-Controller  Health"
  }
 ]
}