{
 "title": "Kubernetes Cluster and Node Health",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Resource Usage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Allocatable CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.node.allocatable.cpuCores",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Total Memory Capacity",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.node.capacity.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Total Pod CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Total Pod CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  { "title": "My Panel", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 }, "content": "## Memory" },
  { "title": "My Panel", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "## CPU" },
  {
   "title": "Total Pod Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 16 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Total Pod Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 16 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "CPU Requests/Limits/Capacity by Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.node.allocatable.cpuCores",
     "timeAggregation": "timeAvg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.node.capacity.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Requests/Limits/Capacity by Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.node.allocatable.memBytes",
     "timeAggregation": "timeAvg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.node.capacity.memBytes",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods per Node",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.status.ready",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.node.allocatable.pods",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.node.capacity.pods",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  { "title": "Capacity Details", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 }, "content": "## Capacity Details" },
  {
   "title": "Total CPU Capacity",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.node.capacity.cpuCores",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Total Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.node.allocatable.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "CPU Requests by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Requests by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Disk Used by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 20,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "fs.bytes.used",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "File I/O by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 20,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Disk Free by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 20,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "asc",
     "target": "fs.bytes.free",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network In by Node",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "net.bytes.in",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Error Count by Node",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "net.error.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Out by Node",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "net.bytes.out",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU Capacity vs Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "cpu.cores.used",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.node.allocatable.cpuCores",
     "timeAggregation": "timeAvg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.node.capacity.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  { "title": "Pods Status", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 108 }, "content": "## Pods Status" },
  {
   "title": "Pods Ready by Daemonsets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 113 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.daemonSet.pods.ready",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pods Desired by Daemonsets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 110 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.daemonSet.pods.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU Used Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pods Desired by StatetefulSets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 110 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.namespace.statefulSet.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Desired by ReplicaSets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 110 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.replicaSet.replicas.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Ready by ReplicaSet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 113 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.replicaSet.replicas.running",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "My Panel (2)",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "content": "**Total CPU Capacity** is the CPU capacity that has been reserved for the node including system daemons.\n\n**Total Allocatable CPU** is the CPU which is available for pods excluding system daemons\n\n **Total Pod CPU limit** should be less than the allocatable CPU of the node or cluster.\n\n**Total Pod CPU Requested** is the amount of CPU that will be guaranteed for pods"
  },
  {
   "title": "Mem Capacity vs Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "memory.bytes.used",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.node.allocatable.memBytes",
     "timeAggregation": "timeAvg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.node.capacity.memBytes",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Mem Used & Mem Limit Used Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Memory Text description",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "content": "**Total Memory Capacity** - Memory capacity that has been reserved for the node including system daemons.\n\n**Total Allocatable Memory** - Memory which is available for pods excluding system daemons\n\n**Total Pod Memory limit** should be less than the allocatable memory of the node or cluster.\n\n**Memory Used percent** is total memory percentage of all pods running.  This is not a % against the limits. \n\n**Memory limitUsed percent** is the average memory usage of all pods against their limits"
  },
  { "title": "Disk Details", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 }, "content": "## Disk Details" },
  { "title": "Network Details", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 75 }, "content": "## Network Details" },
  {
   "title": "Pods Status",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 113 },
   "content": "**Pods Ready** should always be less than **Pods Desired**.  **StatefulSets** and **Daemonsets** are only available at the cluster level."
  },
  {
   "title": "Network Status Description",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 88 },
   "content": "These charts depict the Network details for the **Node** or **Cluster**.  \n"
  },
  {
   "title": "Network In by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "net.bytes.in",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Out by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "net.bytes.out",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "content": "These panels depict Disk usage and File I/O by Pod"
  },
  {
   "title": "Top 10 Filesystems by Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "fs.mountDir" ],
     "sortDirection": "desc",
     "target": "fs.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "File System",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "fs.mountDir",
      "fs.device",
      "fs.type"
     ],
     "sortDirection": "desc",
     "target": "fs.bytes.total",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "fs.mountDir",
      "fs.device",
      "fs.type"
     ],
     "sortDirection": "desc",
     "target": "fs.bytes.used",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "fs.mountDir",
      "fs.device",
      "fs.type"
     ],
     "sortDirection": "desc",
     "target": "fs.bytes.free",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "fs.mountDir",
      "fs.device",
      "fs.type"
     ],
     "sortDirection": "desc",
     "target": "fs.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "FS Usage %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "fs.free.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "fs.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  { "title": "FS Usage", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 }, "content": "## FS Usage" },
  {
   "title": "Network Topology",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 99 },
   "content": "<div class=\"text-center muted\"><strong>Topology</strong> cannot be exported from Sysdig Monitor to Grafana.</div>"
  }
 ]
}