{
 "title": "Kubernetes State Overview",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "No. of Deployments",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.namespace.deployment.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "No. of Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.pod.status.ready", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "No. of Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "container.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "No. of ReplicaSets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.namespace.replicaSet.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "No. of Services",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.namespace.service.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "No. of Namespaces",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.namespace.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Container Count by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Restarts by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "kubernetes.pod.restart.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Available by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "kubernetes.deployment.replicas.available",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Unavailable by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "target": "kubernetes.deployment.replicas.unavailable",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}