{
 "title": "Kubernetes Namespace State",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pods Desired by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.namespace.name" ],
     "target": "kubernetes.deployment.replicas.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Unavailable by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.namespace.name" ],
     "target": "kubernetes.deployment.replicas.unavailable",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Available by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.namespace.name" ],
     "target": "kubernetes.deployment.replicas.available",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Paused by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.namespace.name" ],
     "target": "kubernetes.deployment.replicas.paused",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Restarts by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.namespace.name" ],
     "target": "kubernetes.pod.restart.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Status Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "target": "kubernetes.deployment.replicas.running",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "target": "kubernetes.deployment.replicas.updated",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "target": "kubernetes.deployment.replicas.available",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "target": "kubernetes.deployment.replicas.desired",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "target": "kubernetes.deployment.replicas.unavailable",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "target": "kubernetes.deployment.replicas.paused",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pod Capacity Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "cpu.shares.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Container Count by Namespace",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.namespace.name" ],
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "No. of Deployments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.namespace.deployment.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "No. of Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.pod.status.ready", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "No. of Statefulsets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.namespace.statefulSet.count",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}