{
 "title": "Kubernetes Nodes Health",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Resource Usage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU % by Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Memory % by Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "File System % by Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "fs.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Top Nodes by CPU %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "cpu.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Top Nodes by Memory %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "memory.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Top Nodes by File System %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "fs.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Nodes by File I/O Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "file.time.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Nodes by Network Bytes In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "net.bytes.in",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Nodes by Network Bytes Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "net.bytes.out",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Nodes by Network Error",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "net.error.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Container Count by Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "host.hostName" ],
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Nodes by File I/O Error",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "file.error.total.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Restarts by Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.node.name" ],
     "target": "kubernetes.pod.restart.count",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}