{
 "title": "Kubernetes Deployment State",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(kubernetes.deployment.name)"
   }
  ]
 },
 "panels": [
  {
   "title": "No. of Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "filter": "kubernetes.deployment.name = $deployment",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.status.ready",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Container Count by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "kubernetes.deployment.name = $deployment",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Restarts by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "kubernetes.deployment.name = $deployment",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.restart.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Desired by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "kubernetes.deployment.name = $deployment",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Available by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "kubernetes.deployment.name = $deployment",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.available",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Unavailable by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "kubernetes.deployment.name = $deployment",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.unavailable",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Paused by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "filter": "kubernetes.deployment.name = $deployment",
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.paused",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Deployment Status Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.running",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.updated",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.available",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.desired",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.unavailable",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.paused",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pod Capacity Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "cpu.shares.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}