{
 "title": "Kubernetes Namespace Health",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Resource Usage"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Pod CPU Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Total Pod CPU Limits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  { "title": "My Panel", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 }, "content": "## Memory" },
  { "title": "My Panel", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "## CPU" },
  {
   "title": "Total Pod Memory Requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Total Pod Memory Limits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "CPU Requests by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Requests by Pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Disk Used by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 20,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "desc",
     "target": "fs.bytes.used",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "File I/O by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 20,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Disk Free by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 20,
     "segmentBy": [ "kubernetes.node.name" ],
     "sortDirection": "asc",
     "target": "fs.bytes.free",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Error Count by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "net.error.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU Capacity vs Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "cpu.cores.used",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    }
   ]
  },
  { "title": "Pods Status", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 65 }, "content": "## Pods Status" },
  {
   "title": "Pods Ready by Daemonsets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 70 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.daemonSet.pods.ready",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pods Desired by Daemonsets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 67 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.daemonSet.pods.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU Used Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "cpu.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pods Desired by StatetefulSets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 67 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.namespace.statefulSet.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Desired by ReplicaSets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 67 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.replicaSet.replicas.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Ready by ReplicaSet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 70 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "sum",
     "target": "kubernetes.replicaSet.replicas.running",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "My Panel (2)",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "content": "These panels depict **CPU Capacity**  by Requests / Limits"
  },
  {
   "title": "Mem Capacity vs Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "memory.bytes.used",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Mem Used Percent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "sortDirection": "desc",
     "target": "memory.used.percent",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "My Panel (2)",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "content": "These panels depict **Memory Capacity**  by Requests / Limits"
  },
  { "title": "Disk Details", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 }, "content": "## Disk Details" },
  { "title": "Network Details", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 }, "content": "## Network Details" },
  {
   "title": "Pods Status",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
   "content": "**Pods Ready** should always be less than **Pods Desired**.  **StatefulSets** and **Daemonsets** are only available at the cluster level."
  },
  {
   "title": "Network In by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "net.bytes.in",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Out by Pod",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.pod.name" ],
     "sortDirection": "desc",
     "target": "net.bytes.out",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "content": "These panels depict Disk usage and File I/O by Pod"
  },
  {
   "title": "Pod Restarts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 70 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "kubernetes.pod.restart.count", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Pods Status",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "content": "These charts depict the Network details for the Namespace or Service, broken down at the Pod level."
  },
  {
   "title": "Namespace Network Traffic",
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "content": "<div class=\"text-center muted\"><strong>Topology</strong> cannot be exported from Sysdig Monitor to Grafana.</div>"
  },
  { "title": "Deployments", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 75 }, "content": "## Deployment State" },
  {
   "title": "No. of Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 76 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.pod.status.ready", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Container Count by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Desired by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Available by Deployment",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.deployment.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.available",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Deployment Status Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.running",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.updated",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.available",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.desired",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.unavailable",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.deployment.replicas.paused",
     "timeAggregation": "avg"
    }
   ]
  },
  { "title": "StatefulSet", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 91 }, "content": "## StatefulSet State" },
  {
   "title": "Container Count by Statefulset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.statefulSet.name" ],
     "sortDirection": "desc",
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "No. of Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 92 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "avg",
     "target": "kubernetes.statefulSet.status.replicas.ready",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pod Desired by Statefulset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.statefulSet.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.statefulSet.replicas",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods by Statefulset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.statefulSet.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.statefulSet.status.replicas.ready",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pod Capacity Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "cpu.shares.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.statefulSet.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "sortDirection": "desc",
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  { "title": "DaemonSet", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 107 }, "content": "## DaemonSet State" },
  {
   "title": "Pods Ready by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.daemonSet.pods.ready",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Desired by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.daemonSet.pods.desired",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Scheduled by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.daemonSet.pods.scheduled",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Pods Misscheduled by DaemonSet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "kubernetes.daemonSet.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.daemonSet.pods.misscheduled",
     "timeAggregation": "avg"
    }
   ]
  },
  { "title": "Jobs", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 115 }, "content": "## Job State" },
  {
   "title": "No. of Jobs",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 20,
     "segmentBy": [ "kubernetes.namespace.name" ],
     "sortDirection": "desc",
     "target": "kubernetes.job.status.active",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Jobs Completed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 123 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "kubernetes.job.completions", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 116 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.job.numFailed", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "No. of Jobs succeeded",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 116 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.job.numSucceeded", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "No. of desired pods run by jobs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 123 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.job.parallelism", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Pod Requests Total Cores",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "avg",
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pod Limits Total Cores",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 129 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "avg",
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "cpu.quota.used.percent", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Allocatable CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "avg",
     "target": "kubernetes.node.allocatable.cpuCores",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.used.percent", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Allocatable Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "format": "short",
   "targets": [
    {
     "groupAggregation": "avg",
     "target": "kubernetes.node.allocatable.memBytes",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}