{
 "title": "Kubernetes Resource Quota",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.requests.cpu.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.requests.cpu.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Limits CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.limits.cpu.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.limits.cpu.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Requests Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.requests.memory.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.requests.memory.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Limits Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.limits.memory.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.limits.memory.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Requests Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.requests.storage.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.requests.storage.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Config Maps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.configmaps.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.configmaps.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.persistentvolumeclaims.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.persistentvolumeclaims.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.pods.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.pods.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Replication Controllers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.replicationcontrollers.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.replicationcontrollers.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Resource Quotas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.resourcequotas.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.resourcequotas.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.secrets.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.secrets.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.services.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.services.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Services Loadbalancers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.services.loadbalancers.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.services.loadbalancers.used",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Services Nodeports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.services.nodeports.hard",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "target": "kubernetes.resourcequota.services.nodeports.used",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}