{
 "title": "Kubernetes Pod State",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Kubernetes State"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "kubernetes.node.ready",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "sum", "pageLimit": 10, "target": "kubernetes.node.ready", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Pod Capacity Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "cpu.shares.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.cpuCores",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "memory.limit.used.percent",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceRequests.memBytes",
     "timeAggregation": "avg"
    },
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [
      "kubernetes.namespace.name",
      "kubernetes.deployment.name",
      "kubernetes.pod.name",
      "kubernetes.pod.label.status.phase"
     ],
     "target": "kubernetes.pod.resourceLimits.memBytes",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "Container Count by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "sum", "pageLimit": 10, "target": "container.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "No. of Pods",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "kubernetes.pod.status.ready", "timeAggregation": "timeAvg" }
   ]
  }
 ]
}