{
 "title": "Memory",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Hosts & Containers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Avg. Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.bytes.total", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Avg. Resident Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.bytes.used", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Avg. Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.used.percent", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Avg. Swap Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.swap.bytes.used", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Avg. Page Faults",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.pageFault.major", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Avg. Minor Page Faults",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.pageFault.minor", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "memory.bytes.used", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Page Faults Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "memory.pageFault.major", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Memory Usage - Top Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "memory.bytes.used",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Page Faults - Top Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "memory.pageFault.major",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Usage - Top Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "host.hostName" ],
     "target": "memory.bytes.used",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Page Faults - Top Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "host.hostName" ],
     "target": "memory.pageFault.major",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}