{
 "title": "MongoDB",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Applications"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.mongodb.request.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.mongodb.request.time", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Max Request Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "max", "target": "net.mongodb.request.time.worst", "timeAggregation": "max" }
   ]
  },
  {
   "title": "Request Count Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.mongodb.request.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Average and Max Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.mongodb.request.time", "timeAggregation": "avg" },
    { "groupAggregation": "max", "pageLimit": 10, "target": "net.mongodb.request.time.worst", "timeAggregation": "max" }
   ]
  },
  {
   "title": "Top Collections by Number of Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.mongodb.collection" ],
     "target": "net.mongodb.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Top Operations by Number of Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.mongodb.operation" ],
     "target": "net.mongodb.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Slowest Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "max",
     "pageLimit": 10,
     "segmentBy": [ "net.mongodb.collection" ],
     "target": "net.mongodb.request.time.worst",
     "timeAggregation": "max"
    }
   ]
  },
  {
   "title": "Slowest Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "max",
     "pageLimit": 10,
     "segmentBy": [ "net.mongodb.operation" ],
     "target": "net.mongodb.request.time.worst",
     "timeAggregation": "max"
    }
   ]
  },
  {
   "title": "Number of Operations Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.mongodb.operation" ],
     "target": "net.mongodb.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}