{
 "title": "Overview by Container Image",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Hosts & Containers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Container Count by Image",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "container.image" ],
     "target": "container.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Request Time by Image",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.image" ],
     "target": "net.request.time",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Request Count by Image",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "container.image" ],
     "target": "net.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "CPU % by Image",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.image" ],
     "target": "cpu.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory % by Image",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.image" ],
     "target": "memory.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Net Bytes by Image",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.image" ],
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "File System % by Image",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "container.image" ],
     "target": "fs.used.percent",
     "timeAggregation": "avg"
    }
   ]
  }
 ]
}