{
 "title": "Overview",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Network Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.bytes.total", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "In Network Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.bytes.in", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Out Network Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.bytes.out", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "In vs Out Network Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.bytes.in", "timeAggregation": "timeAvg" },
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.bytes.out", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Network Bytes by Application/Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "net.protocol" ],
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Bytes by Process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Bytes by Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "host.hostName" ],
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}