{
 "title": "Overview by Process",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Hosts & Containers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "cpu.used.percent", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "memory.used.percent", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Network Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.bytes.total", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Network Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.connection.count.total", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "fs.used.percent", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "File Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "file.bytes.total", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "cpu.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "memory.used.percent",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Bytes Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Number of Network Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "net.connection.count.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "File Bytes Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "avg",
     "pageLimit": 10,
     "segmentBy": [ "proc.name" ],
     "target": "file.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}