{
 "title": "Overall CI-Pipeline Metrics",
 "tags": [ "CI-Pipeline" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<p style=\"text-align: center;\"><span style=\"font-size: 28pt;\"><strong>CI-Pipeline Metrics</strong></span></p>",
   "targets": [
    {}
   ]
  },
  {
   "title": "Summary Status Microservices Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "summary_table_build_numbers" },
    { "expr": "summary_table_build_statuses" },
    { "expr": "summary_table_build_times" },
    { "expr": "summary_table_unit_tests" },
    { "expr": "summary_table_code_coverage" },
    { "expr": "summary_table_quality_gates" },
    { "expr": "summary_table_fvt_executed" },
    { "expr": "summary_table_fvt_failures" }
   ]
  },
  {
   "title": "Total Number of Pull Requests",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state!=\"created\", event_state!=\"started\"}[24h]))",
     "legendFormat": "Total"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"passed\"}[24h]))",
     "legendFormat": "Passed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"failed\"}[24h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"errored\"}[24h]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"canceled\"}[24h]))",
     "legendFormat": "Canceled"
    }
   ]
  },
  {
   "title": "Number of Pull Requests Today (Per Hour)",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"passed\"}[2h]))",
     "legendFormat": "Passed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"failed\"}[2h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"errored\"}[2h]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"pull_request\", event_state=\"canceled\"}[2h]))",
     "legendFormat": "Canceled"
    }
   ]
  },
  {
   "title": "Total Number of Commits",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state!=\"created\", event_state!=\"started\"}[24h]))",
     "legendFormat": "Total"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"passed\"}[24h]))",
     "legendFormat": "Passed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"failed\"}[24h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"errored\"}[24h]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"canceled\"}[24h]))",
     "legendFormat": "Canceled"
    }
   ]
  },
  {
   "title": "Number of Commits Today (Per Hour)",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"passed\"}[2h]))",
     "legendFormat": "Passed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"failed\"}[2h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"errored\"}[2h]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{event_type=\"commit\", event_state=\"canceled\"}[2h]))",
     "legendFormat": "Canceled"
    }
   ]
  },
  {
   "title": "Promotions to Integration Stage",
   "type": "corpglory-multibar-graph-panel",
   "description": "When a pull request is merged to master, it moves to the Integration Stage of the CI-Pipeline. This graph highlights the number of promotions to the Integration Stage per day.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(avg_over_time(jenkins_build_status[24h]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg_over_time(jenkins_build_status[24h]))",
     "legendFormat": "Success"
    },
    {
     "expr": "count(avg_over_time(jenkins_build_status[24h])) - sum(avg_over_time(jenkins_build_status[24h]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "K8s Cluster Usage Summary",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes) * 100",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable_pods) * 100",
     "legendFormat": "Pod Usage"
    }
   ]
  }
 ]
}