{
 "title": "Pull Request Metrics",
 "tags": [ "CI-Pipeline" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "label_values(repository)" },
   {
    "name": "pr_number",
    "label": "PR Number",
    "query": "label_values({repository=\"$project\"},pullrequest_number)"
   },
   {
    "name": "build_number",
    "label": "Build Number",
    "query": "label_values({pullrequest_number=\"$pr_number\",repository=\"$project\", event_type=\"pull_request\"},build_number)"
   }
  ]
 },
 "panels": [
  {
   "title": "Build Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(travis_build_state{repository=\"$project\",pullrequest_number=\"$pr_number\",build_number=\"$build_number\"})"
    }
   ]
  },
  { "title": "SonarQube Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Quality Gate Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_quality_gate{project=~\"$project\",version=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Bugs and Vulnerabilities",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 3 },
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_issues_with_ratings{key=~\"$project\",version=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 3 },
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_tests{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Unit Tests"
    },
    {
     "expr": "avg_over_time(sonarqube_lines_to_cover{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Lines to Cover"
    },
    {
     "expr": "avg_over_time(sonarqube_lines_to_cover{key=~\"$project\",version=~\"$build_number\"}[15d]) - avg_over_time(sonarqube_uncovered_lines{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Covered Lines"
    },
    {
     "expr": "avg_over_time(sonarqube_uncovered_lines{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Uncovered Lines"
    }
   ]
  },
  {
   "title": "Line Coverage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_line_coverage{name=~\"$project\",version=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Code Coverage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_coverage{key=~\"$project\",version=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_code_smells_with_ratings{key=~\"$project\",version=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Unit Test Success Density",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_test_success_density{name=~\"$project\",version=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Unit Tests",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_skipped_tests{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Skipped"
    },
    {
     "expr": "avg_over_time(sonarqube_tests{key=~\"$project\",version=~\"$build_number\"}[15d]) - avg_over_time(sonarqube_skipped_tests{key=~\"$project\",version=~\"$build_number\"}[15d]) - ((avg_over_time(sonarqube_test_success_density{key=~\"$project\",version=~\"$build_number\"}[15d]) / 100) * avg_over_time(sonarqube_tests{key=~\"$project\",version=~\"$build_number\"}[15d]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "(avg_over_time(sonarqube_test_success_density{key=~\"$project\",version=~\"$build_number\"}[15d]) / 100) * avg_over_time(sonarqube_tests{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Success"
    },
    {
     "expr": "avg_over_time(sonarqube_tests{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Duplicate Line Density",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_duplicated_lines_density{key=~\"$project\",version=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Duplications",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 5, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_duplicated_blocks{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Duplicate Blocks"
    },
    {
     "expr": "avg_over_time(sonarqube_duplicated_lines{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Duplicate Lines"
    },
    {
     "expr": "avg_over_time(sonarqube_duplicated_files{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Duplicate Files"
    }
   ]
  },
  {
   "title": "SonarQube Issues Total",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_wont_fix_issues{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Won't Fix"
    },
    {
     "expr": "avg_over_time(sonarqube_false_positive_issues{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "False Positive"
    },
    {
     "expr": "avg_over_time(sonarqube_confirmed_issues{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Confirmed"
    },
    {
     "expr": "avg_over_time(sonarqube_reopened_issues{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Re-opened"
    },
    {
     "expr": "avg_over_time(sonarqube_open_issues{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "SonarQube Issues Severity",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(sonarqube_blocker_violations{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Blocker Issues"
    },
    {
     "expr": "avg_over_time(sonarqube_critical_violations{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Critical Issues"
    },
    {
     "expr": "avg_over_time(sonarqube_major_violations{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Major Issues"
    },
    {
     "expr": "avg_over_time(sonarqube_minor_violations{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Minor Issues"
    },
    {
     "expr": "avg_over_time(sonarqube_violations{key=~\"$project\",version=~\"$build_number\"}[15d])",
     "legendFormat": "Total Issues"
    }
   ]
  },
  { "title": "PR Stats and FVT Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "PR Review Period",
   "type": "singlestat",
   "description": "The duration from when the PR is created to when it is merged",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 23 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "3600 * max(pr_report_review_hours{pull_request_number=~\"$pr_number\"})"
    }
   ]
  },
  {
   "title": "Functional Test Results (Test Suites)",
   "type": "table",
   "gridPos": { "h": 14, "w": 10, "x": 5, "y": 23 },
   "targets": [
    {
     "expr": "avg_over_time(travis_fvt_testsuites{project=\"$project\", build_number=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Test Cases FVT Results",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "expr": "avg_over_time(travis_fvt_testcases{project=\"$project\", build_number=~\"$build_number\"}[15d])"
    }
   ]
  },
  {
   "title": "Number of Changes per PR",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(pr_report_additions{pull_request_number=~\"$pr_number\"}[15d]) + avg_over_time(pr_report_deletions{pull_request_number=~\"$pr_number\"}[15d])",
     "legendFormat": "Total Changed Lines"
    },
    {
     "expr": "avg_over_time(pr_report_additions{pull_request_number=~\"$pr_number\"}[15d])",
     "legendFormat": "Additions"
    },
    {
     "expr": "avg_over_time(pr_report_deletions{pull_request_number=~\"$pr_number\"}[15d])",
     "legendFormat": "Deletions"
    },
    {
     "expr": "avg_over_time(pr_report_comments{pull_request_number=~\"$pr_number\"}[15d])",
     "legendFormat": "Comments"
    },
    {
     "expr": "avg_over_time(pr_report_commits{pull_request_number=~\"$pr_number\"}[15d])",
     "legendFormat": "Commits"
    },
    {
     "expr": "avg_over_time(pr_report_changed_files{pull_request_number=~\"$pr_number\"}[15d])",
     "legendFormat": "Changed Files"
    },
    {
     "expr": "avg_over_time(pr_report_review_comments{pull_request_number=~\"$pr_number\"}[15d])",
     "legendFormat": "Review Comments"
    }
   ]
  },
  { "title": "Kubernetes Cloud Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Deployment Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "avg(avg_over_time(kube_deployment_status_replicas{deployment=~\"$project\",version=~\"$build_number\"}[1d]))",
     "legendFormat": "  Total Number of Replicas"
    },
    {
     "expr": "avg(avg_over_time(kube_deployment_status_replicas_available{deployment=~\"$project\",version=~\"$build_number\"}[1d]))",
     "legendFormat": " Available Replicas"
    },
    {
     "expr": "avg(avg_over_time(kube_deployment_status_replicas_unavailable{deployment=~\"$project\",version=~\"$build_number\"}[1d]))",
     "legendFormat": " Unavailable Replicas"
    },
    {
     "expr": "avg(avg_over_time(kube_deployment_status_replicas_updated{deployment=~\"$project\",version=~\"$build_number\"}[1d]))",
     "legendFormat": " Updated Replicas"
    },
    {
     "expr": "avg(avg_over_time(kube_deployment_spec_replicas{deployment=~\"$project\",version=~\"$build_number\"}[1d]))",
     "legendFormat": "Pods Required for Deployment"
    }
   ]
  },
  {
   "title": "Container Status $project",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 38 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{container=~\"$project\"})",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{container=~\"$project\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{container=~\"$project\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_running{container=~\"$project\"})",
     "legendFormat": "Running"
    }
   ]
  }
 ]
}