{
 "title": "Service Overview",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Services"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Container Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "container.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Request Count ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "net.request.count", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Request Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "avg", "target": "net.request.time", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Net Cons: In",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "net.connection.count.in", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Net Cons: Out",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "net.connection.count.out", "timeAggregation": "timeAvg" }
   ]
  },
  {
   "title": "Net Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "targets": [
    { "groupAggregation": "sum", "target": "net.error.count", "timeAggregation": "sum" }
   ]
  },
  {
   "title": "Response Times vs Resource Utilization",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.request.time", "timeAggregation": "avg" },
    { "groupAggregation": "avg", "pageLimit": 10, "target": "cpu.used.percent", "timeAggregation": "timeAvg" },
    { "groupAggregation": "avg", "pageLimit": 10, "target": "memory.used.percent", "timeAggregation": "timeAvg" },
    { "groupAggregation": "avg", "pageLimit": 10, "target": "net.bytes.total", "timeAggregation": "timeAvg" },
    { "groupAggregation": "avg", "pageLimit": 10, "target": "file.bytes.total", "timeAggregation": "timeAvg" }
   ]
  }
 ]
}