{
 "title": "Sonarqube Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "projectname",
    "query": "label_values(sonarqube_coverage, key)"
   }
  ]
 },
 "panels": [
  {
   "title": "Code Coverage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sonarqube_coverage{name=~\"$projectname\",}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_vulnerabilities{name=~\"$projectname\",}"
    }
   ]
  },
  {
   "title": "Duplicate Files",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonarqube_duplicated_files{name=~\"$projectname\",}"
    }
   ]
  },
  {
   "title": "Number of Unit Tests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_tests{name=~\"$projectname\"}"
    }
   ]
  },
  {
   "title": "Unit Test Success Density (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sonarqube_test_success_density{name=\"$projectname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bugs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_bugs{name=~\"$projectname\",}"
    }
   ]
  },
  {
   "title": "Duplicate Blocks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonarqube_duplicated_blocks{name=~\"$projectname\"}"
    }
   ]
  },
  {
   "title": "Unit Tests Skipped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sonarqube_skipped_tests{name=~\"$projectname\"}"
    }
   ]
  },
  {
   "title": "SonarQube Violations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_violations{name=~\"$projectname\"}",
     "legendFormat": "Total Violations"
    },
    {
     "expr": "sonarqube_minor_violations{name=~\"$projectname\"}",
     "legendFormat": "Minor Violations"
    },
    {
     "expr": "sonarqube_major_violations{name=~\"$projectname\"}",
     "legendFormat": "Major Violations"
    },
    {
     "expr": "sonarqube_critical_violations{name=~\"$projectname\"}",
     "legendFormat": "Critical Violations"
    },
    {
     "expr": "sonarqube_blocker_violations{name=~\"$projectname\"}",
     "legendFormat": "Blocker Violations"
    }
   ]
  },
  {
   "title": "Test Execution Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonarqube_test_execution_time{name=~\"$projectname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Commented Lines",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_comment_lines{name=~\"$projectname\"}"
    }
   ]
  },
  {
   "title": "Lines to Cover",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sonarqube_lines_to_cover{name=~\"$projectname\"}"
    }
   ]
  }
 ]
}