{
 "title": "Sysdig Agent Summary",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Hosts & Containers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Agent Versions and Metric Limits",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "concat",
     "pageLimit": 10,
     "segmentBy": [
      "host.hostName",
      "host.mac"
     ],
     "target": "agent.version",
     "timeAggregation": "concat"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "host.hostName",
      "host.mac"
     ],
     "target": "metricCount.jmx",
     "timeAggregation": "max"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "host.hostName",
      "host.mac"
     ],
     "target": "metricCount.appCheck",
     "timeAggregation": "max"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "host.hostName",
      "host.mac"
     ],
     "target": "metricCount.statsd",
     "timeAggregation": "max"
    },
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [
      "host.hostName",
      "host.mac"
     ],
     "target": "metricCount.prometheus",
     "timeAggregation": "max"
    }
   ]
  },
  {
   "title": "Agent count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "count", "pageLimit": 10, "target": "host.mac", "timeAggregation": "distinct" }
   ]
  },
  {
   "title": "Container count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "sum", "pageLimit": 10, "target": "container.count", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Container count by host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "host.hostName" ],
     "target": "container.count",
     "timeAggregation": "avg"
    }
   ]
  },
  {
   "title": "System Calls Processed/Dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "dragent.analyzer.n_evts", "timeAggregation": "avg" },
    { "groupAggregation": "max", "pageLimit": 10, "target": "dragent.analyzer.n_drops", "timeAggregation": "max" },
    {
     "groupAggregation": "max",
     "pageLimit": 10,
     "target": "dragent.analyzer.n_drops_buffer",
     "timeAggregation": "max"
    }
   ]
  },
  {
   "title": "Agent Sampling Ratio",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "dragent.analyzer.sr", "timeAggregation": "avg" }
   ]
  },
  {
   "title": "Agent Flush Time (ms)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "groupAggregation": "avg", "pageLimit": 10, "target": "dragent.analyzer.fl.ms", "timeAggregation": "avg" }
   ]
  }
 ]
}