{
 "title": "Top Ports",
 "tags": [
  "Sysdig",
  "Default dashboard",
  "Network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Network Bytes In by Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "net.server.port" ],
     "target": "net.bytes.in",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Bytes Out by Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "net.server.port" ],
     "target": "net.bytes.out",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Network Bytes Total by Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "net.server.port" ],
     "target": "net.bytes.total",
     "timeAggregation": "timeAvg"
    }
   ]
  },
  {
   "title": "Number of Requests by Port",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupAggregation": "sum",
     "pageLimit": 10,
     "segmentBy": [ "net.server.port" ],
     "target": "net.request.count",
     "timeAggregation": "timeAvg"
    }
   ]
  }
 ]
}