{
 "title": "Jenkins Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Runs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_total_total" }
   ]
  },
  {
   "title": "Number of Successful Runs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Number of Failed Runs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    { "expr": "http_requests", "legendFormat": "{{quantile}}" }
   ]
  }
 ]
}