{
 "title": "Microservice Metrics",
 "tags": [ "CI-Pipeline" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Microservice",
    "query": "label_values(travis_build_number,repository)"
   }
  ]
 },
 "panels": [
  { "title": "Pull Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Pull Requests for $project",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"pull_request\", event_state!=\"created\", event_state!=\"started\"}[24h]))",
     "legendFormat": "Total"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"pull_request\", event_state=\"passed\"}[24h]))",
     "legendFormat": "Passed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"pull_request\", event_state=\"failed\"}[24h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"pull_request\", event_state=\"errored\"}[24h]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"pull_request\", event_state=\"canceled\"}[24h]))",
     "legendFormat": "Canceled"
    }
   ]
  },
  {
   "title": "Average Pull Request Size",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "avg(avg_over_time(pr_report_changed_lines{project=~\"$project\", created_at!=\"\"}[24h]))",
     "legendFormat": "Avg PR Size (Lns)"
    }
   ]
  },
  {
   "title": "Pull Request Status",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum (travis_build_number{repository=\"$project\",event_type=\"pull_request\",event_state!=\"started\",event_state!=\"created\"}) by (build_number,event_state,build_id,pullrequest_number,started_at)"
    },
    {
     "expr": "sum (travis_build_pull_request_number{repository=\"$project\",event_type=\"pull_request\",changed_lines!=\"unavailable\"}) by (build_number,event_state,build_id,changed_lines)"
    }
   ]
  },
  {
   "title": "Passed PR Build Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(travis_build_duration{repository=~\"$project\", event_type=\"pull_request\", event_state=\"passed\"}[24h]))"
    }
   ]
  },
  {
   "title": "Failed PR Build Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 12 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(travis_build_duration{repository=~\"$project\", event_type=\"pull_request\", event_state=\"failed\"}[24h]))"
    }
   ]
  },
  {
   "title": "Errored PR Build Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 12 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(travis_build_duration{repository=~\"$project\", event_type=\"pull_request\", event_state=\"errored\"}[24h]))"
    }
   ]
  },
  { "title": "Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number of Commits for $project",
   "type": "corpglory-multibar-graph-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"commit\", event_state!=\"created\", event_state!=\"started\"}[24h]))",
     "legendFormat": "Total"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"commit\", event_state=\"passed\"}[24h]))",
     "legendFormat": "Passed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"commit\", event_state=\"failed\"}[24h]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"commit\", event_state=\"errored\"}[24h]))",
     "legendFormat": "Errored"
    },
    {
     "expr": "count(increase(travis_build_pull_request_number{repository=~\"$project\", event_type=\"commit\", event_state=\"canceled\"}[24h]))",
     "legendFormat": "Canceled"
    }
   ]
  },
  {
   "title": "Passed Commits Build Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(travis_build_duration{repository=~\"$project\", event_type=\"commit\", event_state=\"passed\"}[24h]))"
    }
   ]
  },
  {
   "title": "Commit Status",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "max_over_time(travis_build_pull_request_number{repository=~\"$project\", event_type=\"commit\",event_state!=\"started\", changed_lines!=\"unavailable\"}[15d])"
    }
   ]
  },
  {
   "title": "Failed Commits Build Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 21 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(travis_build_duration{repository=~\"$project\", event_type=\"commit\", event_state=\"failed\"}[24h]))"
    }
   ]
  },
  {
   "title": "Errored Commits Build Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 25 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(travis_build_duration{repository=~\"$project\", event_type=\"commit\", event_state=\"errored\"}[24h]))"
    }
   ]
  },
  { "title": "Defects and Bugs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Defects for $project",
   "type": "table",
   "description": "Duration (in hours) from when a defect is opened to when it is closed.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum (defect_duration_hours{project=\"$project\"}) by (defect_number,title)"
    },
    {
     "expr": "sum (defect_created_at{project=\"$project\"}) by (defect_number,title) * 1000"
    }
   ]
  },
  {
   "title": "Integration Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Integration Builds",
     "type": "corpglory-multibar-graph-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(avg_over_time(jenkins_build_status{project=~\"$project\"}[24h]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(avg_over_time(jenkins_build_status{project=~\"$project\"}[24h]))",
       "legendFormat": "Passed"
      },
      {
       "expr": "count(avg_over_time(jenkins_build_status{project=~\"$project\"}[24h])) - sum(avg_over_time(jenkins_build_status{project=~\"$project\"}[24h]))",
       "legendFormat": "Failed"
      }
     ]
    },
    {
     "title": "Integration Build Statuses",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "avg_over_time(jenkins_build_status{project=~\"$project\"}[15d])"
      }
     ]
    }
   ]
  },
  { "title": "K8s Deployments and Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Deployment Replicas",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"$project\"}",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=~\"$project\"})",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"$project\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"$project\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Pod Statuses",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Unknown\"})",
     "legendFormat": "Pods Unknown"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Pending\"})",
     "legendFormat": "Pods Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Failed\"})",
     "legendFormat": "Pods Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Succeeded\"})",
     "legendFormat": "Pods Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"default\", phase=\"Running\"})",
     "legendFormat": "Pods Running"
    }
   ]
  }
 ]
}